Make sync prefer system python instead of uv managed
tox-dev/tox-uv pull request #148
Opened 2024-12-28 13:25 UTC by ssbarnea

Fixes: #110

2024-12-28 15:29 UTC, gaborbernat commented
I do not want to hardcode this. I want user to be able to change it, so at the very least should be configurable.

2024-12-28 15:40 UTC, ssbarnea commented
Doable, no problem. Still, I think that we need to alter the default to ensure the uv will prefer system instead of managed (unless configured). Otherwise, users will face broken like the bug this change is supposed to fix.

2024-12-30 01:32 UTC, gaborbernat requested changes
CI failing.

2025-01-16 15:31 UTC, ssbarnea commented
Last failure is related to https://github.com/iarna/iarna-toml/issues/48 and https://github.com/astral-sh/setup-uv/issues/242 - i will make a patch to stick to older versions with setup-uv for now. Now I am happy that I never used that action myself, did the install manually.

2025-01-16 16:30 UTC, gaborbernat approved these changes

2025-01-16 16:31 UTC, gaborbernat requested changes
type check failure

2025-01-16 17:31 UTC, merged